### ISSUE TITLE
Battery references goes blank

### ISSUE THREAD

**Issue by riksarchen** [jonasbkarlsson/ferroamp_operation_settings#30]
Not sure if I'm doing something wrong but when I update my ace threshold for example my battery references goes to 0/0 even though I have the references set and they read correctly from the portal. 

Im using the fields charge reference and discharge reference. 

I also have charge threshold and discharge threshold but I don't know what that's for?

**Comment by jonasbkarlsson** [comment]
Which "Mode" are using?

Can you clarify what you mean by "battery references"? Do you mean the "Lower Reference" and "Upper Reference"?

Note that "Update" sends all parameter values to the portal, so to be safe, it's a good idea to do "Get Data", change parameters, "Update".

**Comment by riksarchen** [comment]
I mean the max charge and discharge rates for the battery. I'm using self-consumption and even if I "get data" first it still sends 0/0 to the portal

**Comment by jonasbkarlsson** [comment]
Hmm. Seems like Ferroamp might have changed the login prodecure. The current implementation is not able to login any more.

**Comment by jonasbkarlsson** [comment]
Fixed in [v1.2.0](https://github.com/jonasbkarlsson/ferroamp_operation_settings/releases/tag/v1.2.0).

**Comment by riksarchen** [comment]
Thanks a lot! Works perfectly now
