### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by zgnusrx** [jonasbkarlsson/ferroamp_operation_settings#45]
Hey Jonas,

I get login failed. I have checked and double checked my information is correct.

Log: Failed to receive authorization code

Any suggestions?

**Comment by jonasbkarlsson** [comment]
Do you have access to mutiple Ferroamp systems with your login? Currently, that is not supported by the integration.

**Comment by jonasbkarlsson** [comment]
Kan du skicka ett mail till jonas.b.karlsson (at) gmail.com   ?

**Comment by jonasbkarlsson** [comment]
Fixed in Release [v1.5.0](https://github.com/jonasbkarlsson/ferroamp_operation_settings/releases/tag/v1.5.0)
