### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by zgnusrx** [jonasbkarlsson/ferroamp_operation_settings#54]
Afternoon,

Suspect FA changed login procedure again.

Script gets login failed when reconfiguring, and trying "get data" results in "Failed to perform the action button/press. 'NoneType' object is not subscriptable"

**Comment by jonasbkarlsson** [comment]
Thanks for reporting. Will check.

**Comment by jonasbkarlsson** [comment]
Ferroamp has updated the terms and conditions for using the portal. Please login using a web browser and approve the new agreement. After that, the integration will work again.

**Comment by jonasbkarlsson** [comment]
Made an v1.6.1 that detects the need of extra action from the user, and creates an error message in the HA logs.
